#기본적인 설정파일
#데이터 설정
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  #springboot 메뉴얼에서 공부해야 함
  jpa:
    hibernate:
      ddl-auto: create

      #자동으로 테이블 만들어줌
      #애플리케이션 실행 시점에 내가 가지고 있는 테이블을 다 지우고, 다시 생성

      #hibernate와 관련된 특정한 properties 사용할 수 있음
    properties:
      hibernate:
        # show_sql: true 시스템 아웃에서 출력됨
        format_sql: true
#  mvc:
#    static-path-pattern: resources

logging.level:
  #로그를 통해 출력
  org.hibernate.SQL: debug
  #1번 파라미터는 ~, 2번 파라미터는 ~ ~~ 찍어줌
  org.hibernate.type: trace

